# read data and clean data

In [1]:
import pandas as pd 
import numpy as np 

trainTable = pd.read_csv("train.csv", engine = "python", encoding = "big5")

trainTable.head(18)


日期  測站          測項     0     1     2     3     4     5     6  ...  \
0   2014/1/1  豐原    AMB_TEMP    14    14    14    13    12    12    12  ...   
1   2014/1/1  豐原         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8  ...   
2   2014/1/1  豐原          CO  0.51  0.41  0.39  0.37  0.35   0.3  0.37  ...   
3   2014/1/1  豐原        NMHC   0.2  0.15  0.13  0.12  0.11  0.06   0.1  ...   
4   2014/1/1  豐原          NO   0.9   0.6   0.5   1.7   1.8   1.5   1.9  ...   
5   2014/1/1  豐原         NO2    16   9.2   8.2   6.9   6.8   3.8   6.9  ...   
6   2014/1/1  豐原         NOx    17   9.8   8.7   8.6   8.5   5.3   8.8  ...   
7   2014/1/1  豐原          O3    16    30    27    23    24    28    24  ...   
8   2014/1/1  豐原        PM10    56    50    48    35    25    12     4  ...   
9   2014/1/1  豐原       PM2.5    26    39    36    35    31    28    25  ...   
10  2014/1/1  豐原    RAINFALL    NR    NR    NR    NR    NR    NR    NR  ...   
11  2014/1/1  豐原          RH    77    68    67    74    72    73    74  ...   
12  2014/1/1  豐原         SO2   1.8     2   1.7   1.6   1.9   1.4   1.5  ...   
13  2014/1/1  豐原         THC     2     2     2   1.9   1.9   1.8   1.9  ...   
14  2014/1/1  豐原       WD_HR    37    80    57    76   110   106   101  ...   
15  2014/1/1  豐原  WIND_DIREC    35    79   2.4    55    94   116   106  ...   
16  2014/1/1  豐原  WIND_SPEED   1.4   1.8     1   0.6   1.7   2.5   2.5  ...   
17  2014/1/1  豐原       WS_HR   0.5   0.9   0.6   0.3   0.6   1.9     2  ...   

      14    15    16    17    18    19    20    21    22    23  
0     22    22    21    19    17    16    15    15    15    15  
1    1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8  
2   0.37  0.37  0.47  0.69  0.56  0.45  0.38  0.35  0.36  0.32  
3    0.1  0.13  0.14  0.23  0.18  0.12   0.1  0.09   0.1  0.08  
4    2.5   2.2   2.5   2.3   2.1   1.9   1.5   1.6   1.8   1.5  
5     11    11    22    28    19    12   8.1     7   6.9     6  
6     14    13    25    30    21    13   9.7   8.6   8.7   7.5  
7     65    64    51    34    33    34    37    38    38    36  
8     52    51    66    85    85    63    46    36    42    42  
9     36    45    42    49    45    44    41    30    24    13  
10    NR    NR    NR    NR    NR    NR    NR    NR    NR    NR  
11    47    49    56    67    72    69    70    70    70    69  
12   3.9   4.4   9.9   5.1   3.4   2.3     2   1.9   1.9   1.9  
13   1.9   1.9   1.9   2.1     2   1.9   1.9   1.9   1.9   1.9  
14   307   304   307   124   118   121   113   112   106   110  
15   313   305   291   124   119   118   114   108   102   111  
16   2.5   2.2   1.4   2.2   2.8     3   2.6   2.7   2.1   2.1  
17   2.1   2.1   1.9     1   2.5   2.5   2.8   2.6   2.4   2.3  

[18 rows x 27 columns]

In [2]:
trainTable.shape

(4320, 27)

In [3]:
trainDataTable = trainTable["0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23".split(" ")]
trainDataTable = trainDataTable.replace("NR", "0").astype("float")

In [4]:
trainIndex1 = (trainDataTable.shape[0] // 18 // 3) * 18
trainIndex2 = (trainDataTable.shape[0] // 18 // 3) * 2 * 18

train1 = trainDataTable.iloc[0:trainIndex1, :]
train2 = trainDataTable.iloc[trainIndex1:trainIndex2, :]
testSet = trainDataTable.iloc[trainIndex2:, :]

In [5]:
print(train1.shape)
print(train2.shape)
print(testSet.shape)

(1440, 24)
(1440, 24)
(1440, 24)


In [6]:
# this is for mean model 
def readData(df, rowStep, columnStep):
    xList = []
    yList = []
    shape = df.shape
    columns = shape[1]
    rows = shape[0]
    for i in range(0, rows, rowStep):
        for j in range(0, columns - columnStep):  # looping for 15 column
            dataset = df.iloc[i: i + rowStep, j:j + 9]
            dataset.astype("float32")
            pm = df.iloc[i + 9, j + 9]
            npArr = np.array(dataset).astype("float32")
            avgArr = npArr.mean(axis = 1)
            avgArr = avgArr.reshape(18,1)
            xList.append(avgArr)
            yList.append(float(pm))
    
    return xList, yList


In [7]:

realMeanModelX1, realMeanModelY1 = readData(train1, 18, 9)
realMeanModelX2, realMeanModelY2 = readData(train2, 18, 9)
realMeanModelXAll, realMeanModelYAll = readData(pd.concat([train1, train2]), 18, 9)


In [20]:
realMeanModelYAll[0:5]

[30.0, 41.0, 44.0, 33.0, 37.0]

In [9]:
realMeanModelXAll[0:3]

[array([[13.111111  ],
        [ 1.8000001 ],
        [ 0.43888888],
        [ 0.14      ],
        [ 1.9666666 ],
        [ 8.955556  ],
        [10.955555  ],
        [23.88889   ],
        [27.        ],
        [28.777779  ],
        [ 0.        ],
        [71.55556   ],
        [ 2.0666666 ],
        [ 1.9444444 ],
        [88.333336  ],
        [90.37778   ],
        [ 1.5666667 ],
        [ 1.0333333 ]], dtype=float32),
 array([[ 13.444445  ],
        [  1.8000001 ],
        [  0.4644445 ],
        [  0.14333333],
        [  2.7444444 ],
        [  9.511111  ],
        [ 12.288889  ],
        [ 25.333334  ],
        [ 25.        ],
        [ 29.222221  ],
        [  0.        ],
        [ 69.22222   ],
        [  3.5333335 ],
        [  1.9444444 ],
        [ 89.333336  ],
        [103.48889   ],
        [  1.5000001 ],
        [  1.0111111 ]], dtype=float32),
 array([[ 14.111111  ],
        [  1.8000001 ],
        [  0.48444447],
        [  0.14888889],
        [  3.1444445 ],


In [10]:
# find the mean for all data 
# find the standard deviation 

def getMean(df, arr):
    output = []
    for label in arr:
        print(label)
        labelDf = df.loc[:,label,:]
        avg = np.array(labelDf, dtype = "float").mean()
        print("avg = " + str(avg))
        output.append(avg)
    return output

def getDV(df, arr):
    output = []
    for label in arr:
        print(label)
        labelDf = df.loc[:,label,:]
        avg = np.array(labelDf, dtype = "float").std()
        print("avg = " + str(avg))
        output.append(avg)
    return output

In [11]:
trainTable.replace("NR", "0", inplace = True)
indexTable = trainTable.set_index(["日期", "測項"])
indexDropTable = indexTable.drop(["測站"], axis=1)  

meanArr = getMean(indexDropTable, ["CH4", "CO", "NO", "NO2", "PM2.5", "RAINFALL"])
stdArr = getDV(indexDropTable, ["CH4", "CO", "NO", "NO2", "PM2.5", "RAINFALL"])

CH4
avg = 1.702395833333333
CO
avg = 0.38836284722222225
NO
avg = 2.1357291666666667
NO2
avg = 10.125989583333332
PM2.5
avg = 21.414236111111112
RAINFALL
avg = 0.200625
CH4
avg = 0.12525455850819694
CO
avg = 0.32354456739666226
NO
avg = 2.2819569657020202
NO2
avg = 6.187017929584704
PM2.5
avg = 16.661090903986995
RAINFALL
avg = 2.0452654401045627


In [12]:
def getstdDistribution(df, indexArr, meanArr, stdArr):
    output = []
    index = 0
    for i in indexArr:
        row = df.iloc[i,:]
        row = (row - meanArr[index]) / stdArr[index]
        output.append(row)
        index = index + 1
    return output
    

In [13]:
# this is for model 2 
# CH4, CO, NO, NO2, PM 2.5, Rain fall

def readData2(df, rowStep, columnStep, meanArr, stdArr):
    xList = []
    yList = []
    shape = df.shape
    columns = shape[1]
    rows = shape[0]
    for i in range(0, rows, rowStep):
        for j in range(0, columns - columnStep):  # looping for 15 column
            dataset = df.iloc[i: i + rowStep, j:j + 9]
            pm = df.iloc[i + 9, j + 9]
            arr = getstdDistribution(dataset, [1,2,4,5,9,10], meanArr, stdArr)
            npArr = np.array(arr)
            xList.append(npArr.reshape(npArr.shape[0] * npArr.shape[1], 1))
            yList.append(float(pm))
    
    return xList, yList

In [14]:
def getPower(x):
    outputList = []
    for i in range(len(x)):
        arr = x[i]
        arr.reshape((18,1))
        power2 = np.power(arr, 2)
        power3 = np.power(arr, 3)
        arr = np.vstack((arr, power2, power3))
        outputList.append(arr)
    
    return outputList

In [16]:
realModelX1, realModelY1 = readData2(train1, 18, 9, meanArr, stdArr)
realModelX2, realModelY2 = readData2(train2, 18, 9, meanArr, stdArr)
realModelXAll, realModelYAll = readData2(pd.concat([train1, train2]), 18, 9, meanArr, stdArr)

In [18]:
print(len(realModelXAll))   # check data
print(len(realModelYAll))
print(realModelX2[1199])
print(realModelY2[1199])

2400
2400
[[-0.01912771]
 [-0.01912771]
 [-0.01912771]
 [-0.01912771]
 [-0.01912771]
 [-0.01912771]
 [-0.01912771]
 [-0.01912771]
 [-0.01912771]
 [-0.61309281]
 [-0.42764695]
 [-0.24220109]
 [ 0.06687534]
 [-0.05675523]
 [-0.36583166]
 [-0.55127752]
 [-0.70581574]
 [-0.76763102]
 [-0.14712336]
 [ 3.44628359]
 [ 0.11580886]
 [-0.23476743]
 [-0.27858946]
 [-0.05947928]
 [-0.3224115 ]
 [-0.36623354]
 [-0.41005557]
 [-0.65071568]
 [ 0.78778023]
 [ 0.46452272]
 [ 0.46452272]
 [ 0.46452272]
 [-0.18199229]
 [-0.66687856]
 [-0.84467019]
 [-1.10327619]
 [-0.38498296]
 [-0.8651436 ]
 [-0.74510344]
 [-0.50502312]
 [-0.02486248]
 [-0.2649428 ]
 [-0.32496288]
 [-0.80512352]
 [-0.80512352]
 [-0.0980924 ]
 [-0.0980924 ]
 [-0.0980924 ]
 [-0.0980924 ]
 [-0.0980924 ]
 [-0.0980924 ]
 [-0.0980924 ]
 [-0.0980924 ]
 [-0.0980924 ]]
3.0


# finish cleaning and getting data 

# start inital training

In [21]:
learningRate = 0.9
regulationRate = 0.00001
epoch = 1000


# loss = (y - y1)^2 + sum(wi^2)
# y1 = w1 * x1 + w2 * x1^2 + w3 * x1^3 + w4 * x2 + w5 * x2^2 ..... + b

# in other way for wn
# loss = (cn * wn + c2)^2 + regRate * wn^2 + c3

# so
# dloss/dw = 2(cn * wn + c2) * cn + 2regRate * wn

# for b 
# loss = (c + b)^2 + c1
# dloss/db = 2[c + b]

def sgdm(realX, realY, learningRate, regRate, epoch, experience):
    w = np.random.randn(1, len(realX[0]))
    b = np.random.rand(1,1)
    print("w = ")
    print(w, "\n")
    print("b = ")
    print(b, "\n")
    
    mw = 0  # momanton
    mb = 0
    for i in range(epoch):
        errorW = np.zeros((1, w.shape[1]))
        errorB = 0
        for j in range(len(realY)): # looping number of dataset
            errorW = errorW + (2 * (np.dot(w, realX[j]) + b - realY[j]) * realX[j].T) + w * regRate
            errorB = errorB + (2 * (np.dot(w, realX[j]) + b - realY[j]))
            
        avgErrorB = errorB / len(realY)
        avgErrorW = errorW / len(realY)
            
#         print loss
        if i % 50 == 0:
            loss = (np.dot(w, realX[j]) + b - realY[j])**2
            print("loss = " + str(loss))  
            
#         updating
        mb = experience * mb + (1 - experience) * avgErrorB    
        b = b - mb * learningRate
        mw = experience * mw + (1 - experience) * avgErrorW   
        w = w - mw * learningRate
        
    return w, b
    

# start training

In [22]:
learningRate = 0.000001
regulationRate = 0.00001
epoch = 1000

# loss = (y - y1)^2 + sum(wi^2)
# y1 = w1 * x1 + w2 * x1^2 + w3 * x1^3 + w4 * x2 + w5 * x2^2 ..... + b

# in other way for wn
# loss = (cn * wn + c2)^2 + regRate * wn^2 + c3

# so
# dloss/dw = 2(cn * wn + c2) * cn + 2regRate * wn

# for b 
# loss = (c + b)^2 + c1
# dloss/db = 2[c + b]

def train2(realX, realY, learningRate, regRate, epoch):
    w = np.random.randn(1, len(realX[0]))
    b = np.random.rand(1,1)
    print("w = ")
    print(w, "\n")
    print("b = ")
    print(b, "\n")
    for i in range(epoch):
        errorW = np.zeros((1, w.shape[1]))
        errorB = 0
        for j in range(len(realY)): # looping number of dataset
            errorW = errorW + (2 * (np.dot(w, realX[j]) + b - realY[j]) * realX[j].T) + w * regRate
            errorB = errorB + (2 * (np.dot(w, realX[j]) + b - realY[j]))
            
        avgErrorB = errorB / len(realY)
        avgErrorW = errorW / len(realY)
            
#         print loss
        if i % 50 == 0:
            loss = (np.dot(w, realX[j]) + b - realY[j])**2
            print("loss = " + str(loss))  
            
#         updating
        b = b - avgErrorB * learningRate
        w = w - avgErrorW * learningRate
        
    return w, b
    

In [28]:
train2(realMeanModelXAll, realMeanModelYAll, 0.0000001, 0.00001, 1000)

w = 
[[ 1.39398767  1.11490822 -0.52781445 -0.70146838 -0.52321496  1.76502576
   0.59650673 -2.00390498  0.25987774  0.5869625  -0.02248162  0.57016791
   0.03236885 -1.18298217 -0.58260899  0.84768594  0.32512165  0.28007503]] 

b = 
[[0.8847871]] 

loss = [[10902.66611828]]
loss = [[3649.04968995]]
loss = [[1714.09467036]]
loss = [[1100.31280872]]
loss = [[875.21632578]]
loss = [[783.92420399]]
loss = [[743.98407012]]
loss = [[724.98939554]]
loss = [[714.80547135]]
loss = [[708.38994392]]
loss = [[703.60750724]]
loss = [[699.54610775]]
loss = [[695.81460079]]
loss = [[692.2448401]]
loss = [[688.76436606]]
loss = [[685.34182037]]
loss = [[681.96350873]]
loss = [[678.62333132]]
loss = [[675.31845522]]
loss = [[672.04745437]]


(array([[ 1.36216789,  1.11243984, -0.5282998 , -0.7017904 , -0.53017065,
          1.74651126,  0.57106041, -1.97111278,  0.24505775,  0.59066903,
         -0.0245599 ,  0.41361707,  0.03005342, -1.18575731, -0.72050595,
          0.62737943,  0.32211061,  0.27755482]]),
 array([[0.88332314]]))

In [29]:
wM1, bM1= sgdm(realMeanModelXAll, realMeanModelYAll, 0.000005, 0.00001, 3000, 0.9)

w = 
[[ 0.85618864  0.46422992  1.41636754  0.31264957 -0.87742244  0.71930221
   0.13829765  1.06799775  0.97583779  1.30736778 -0.88585064 -1.00073925
  -0.40319955 -1.4143598   0.47879641 -0.79324242 -0.62899596 -1.1126545 ]] 

b = 
[[0.72832288]] 

loss = [[1089.27703578]]
loss = [[5.97844628]]
loss = [[10.89362306]]
loss = [[56.60501133]]
loss = [[107.72265576]]
loss = [[150.0911824]]
loss = [[181.41070761]]
loss = [[202.99050926]]
loss = [[217.0397392]]
loss = [[225.63720454]]
loss = [[230.44202531]]
loss = [[232.68245615]]
loss = [[233.23072753]]
loss = [[232.69044217]]
loss = [[231.47193149]]
loss = [[229.85029438]]
loss = [[228.00765828]]
loss = [[226.06299046]]
loss = [[224.09272548]]
loss = [[222.1448635]]
loss = [[220.24852719]]
loss = [[218.42040272]]
loss = [[216.66906119]]
loss = [[214.9978467]]
loss = [[213.40679887]]
loss = [[211.89392661]]
loss = [[210.45604726]]
loss = [[209.08933494]]
loss = [[207.78967492]]
loss = [[206.55288888]]
loss = [[205.37487468]]
loss = [[2

In [45]:
w1, b1 = sgdm(realModelXAll, realModelYAll, 0.00001, 0.00001, 1000, 0.99)

w = 
[[-0.42879104  0.38314708  1.95859684  0.78919372  0.68220934 -0.66642182
  -0.52157485  1.1060146  -1.23680563 -1.08493938  0.56808821  1.47421795
  -1.36299382 -1.19857466 -0.27959047  0.29681526  0.7112442  -1.25401756
   2.94435594  1.67185341  1.29534828 -0.25425276 -0.88484839  0.50110611
  -1.03624839 -0.11986846 -0.1715203  -0.15382751  1.60597879 -1.19935602
  -0.39200548 -1.48242079  0.77205063 -0.11860166  1.35527121 -0.46920867
   0.41540456  0.72600022 -0.93418724 -0.85708276 -1.36707767  0.44805094
   1.35208342  1.00208081 -0.11794212 -1.07948424 -0.89615013 -0.28725414
   0.43583164  0.18002676  1.03537879  0.44349291 -0.61089105  1.28468398]] 

b = 
[[0.2040477]] 

loss = [[4.46628317]]
loss = [[4.36856493]]
loss = [[4.13725417]]
loss = [[3.83512415]]
loss = [[3.5013684]]
loss = [[3.15961584]]
loss = [[2.82371933]]
loss = [[2.50156345]]
loss = [[2.19745396]]
loss = [[1.91357769]]
loss = [[1.65088027]]
loss = [[1.4095881]]
loss = [[1.18951665]]
loss = [[0.99025142]

In [35]:
def getAvgError(w, b, dataX, dataY):
    error = 0
    for i in range(len(dataY)):
        y = (np.dot(w, dataX[i]) + b)
        error = error + abs(dataY[i] - y)
    return error / len(dataY)

In [36]:
getAvgError(wM1, bM1, realMeanModelX1, realMeanModelY1)

array([[9.84149147]])

In [37]:
getAvgError(wM1, bM1, realMeanModelX2, realMeanModelY2)

array([[8.56323986]])

In [46]:
getAvgError(w1, b1, realModelX1, realModelY1)

array([[26.63273952]])

In [52]:
getAvgError(w1, b1, realModelX2, realModelY2)

array([[20.05396614]])

In [49]:
testMeanX, testMeanY = readData(testSet, 18, 9)
testRealX, testRealY = readData2(testSet, 18, 9, meanArr, stdArr)

In [50]:
getAvgError(wM1, bM1, testMeanX, testMeanY)

array([[9.40073307]])

In [51]:
getAvgError(w1, b1, testRealX, testRealY)

array([[22.70061986]])

mean model seen like look better so output mean model

In [53]:
wdf = pd.DataFrame(wM1)
bdf = pd.DataFrame(bM1)
wdf.to_csv("weights.csv")
bdf.to_csv("bias.csv")