# read data and clean data

In [1]:
import pandas as pd 
import numpy as np 

trainTable = pd.read_csv("train.csv", engine = "python", encoding = "big5")

trainTable.head(18)


日期  測站          測項     0     1     2     3     4     5     6  ...  \
0   2014/1/1  豐原    AMB_TEMP    14    14    14    13    12    12    12  ...   
1   2014/1/1  豐原         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8  ...   
2   2014/1/1  豐原          CO  0.51  0.41  0.39  0.37  0.35   0.3  0.37  ...   
3   2014/1/1  豐原        NMHC   0.2  0.15  0.13  0.12  0.11  0.06   0.1  ...   
4   2014/1/1  豐原          NO   0.9   0.6   0.5   1.7   1.8   1.5   1.9  ...   
5   2014/1/1  豐原         NO2    16   9.2   8.2   6.9   6.8   3.8   6.9  ...   
6   2014/1/1  豐原         NOx    17   9.8   8.7   8.6   8.5   5.3   8.8  ...   
7   2014/1/1  豐原          O3    16    30    27    23    24    28    24  ...   
8   2014/1/1  豐原        PM10    56    50    48    35    25    12     4  ...   
9   2014/1/1  豐原       PM2.5    26    39    36    35    31    28    25  ...   
10  2014/1/1  豐原    RAINFALL    NR    NR    NR    NR    NR    NR    NR  ...   
11  2014/1/1  豐原          RH    77    68    67    74    72    73    74  ...   
12  2014/1/1  豐原         SO2   1.8     2   1.7   1.6   1.9   1.4   1.5  ...   
13  2014/1/1  豐原         THC     2     2     2   1.9   1.9   1.8   1.9  ...   
14  2014/1/1  豐原       WD_HR    37    80    57    76   110   106   101  ...   
15  2014/1/1  豐原  WIND_DIREC    35    79   2.4    55    94   116   106  ...   
16  2014/1/1  豐原  WIND_SPEED   1.4   1.8     1   0.6   1.7   2.5   2.5  ...   
17  2014/1/1  豐原       WS_HR   0.5   0.9   0.6   0.3   0.6   1.9     2  ...   

      14    15    16    17    18    19    20    21    22    23  
0     22    22    21    19    17    16    15    15    15    15  
1    1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8  
2   0.37  0.37  0.47  0.69  0.56  0.45  0.38  0.35  0.36  0.32  
3    0.1  0.13  0.14  0.23  0.18  0.12   0.1  0.09   0.1  0.08  
4    2.5   2.2   2.5   2.3   2.1   1.9   1.5   1.6   1.8   1.5  
5     11    11    22    28    19    12   8.1     7   6.9     6  
6     14    13    25    30    21    13   9.7   8.6   8.7   7.5  
7     65    64    51    34    33    34    37    38    38    36  
8     52    51    66    85    85    63    46    36    42    42  
9     36    45    42    49    45    44    41    30    24    13  
10    NR    NR    NR    NR    NR    NR    NR    NR    NR    NR  
11    47    49    56    67    72    69    70    70    70    69  
12   3.9   4.4   9.9   5.1   3.4   2.3     2   1.9   1.9   1.9  
13   1.9   1.9   1.9   2.1     2   1.9   1.9   1.9   1.9   1.9  
14   307   304   307   124   118   121   113   112   106   110  
15   313   305   291   124   119   118   114   108   102   111  
16   2.5   2.2   1.4   2.2   2.8     3   2.6   2.7   2.1   2.1  
17   2.1   2.1   1.9     1   2.5   2.5   2.8   2.6   2.4   2.3  

[18 rows x 27 columns]

In [2]:
trainTable.shape

(4320, 27)

In [3]:
trainTable.iloc[4319, :]

日期    2014/12/20
測站            豐原
測項         WS_HR
0            0.7
1            0.8
2            1.8
3              1
4            1.9
5            1.7
6            2.1
7              2
8              2
9            1.7
10             3
11           2.9
12           2.7
13           2.8
14           1.3
15           1.7
16           0.7
17           0.4
18           1.1
19           1.4
20           1.3
21           1.6
22           1.8
23             2
Name: 4319, dtype: object

In [4]:
def readData(df, rowStep, columnStep):
    xList = []
    yList = []
    shape = df.shape
    columns = shape[1]
    rows = shape[0]
    for i in range(0, rows, rowStep):
        for j in range(0, columns - columnStep):  # looping for 15 column
            dataset = df.iloc[i: i + rowStep, j:j + 9]
            dataset.astype("float32")
            pm = df.iloc[i + 9, j + 9]
            npArr = np.array(dataset).astype("float32")
            avgArr = npArr.mean(axis = 1)
            avgArr = avgArr.reshape(18,1)
            xList.append(avgArr)
            yList.append(float(pm))
    
    return xList, yList


In [5]:
trainDataTable = trainTable["0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23".split(" ")]
trainDataTable.replace("NR", "0", inplace = True)
realX, realY = readData(trainDataTable, 18, 9)


C:\Users\Arvin\AppData\Roaming\Python\Python38\site-packages\pandas\core\frame.py:4373: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(


In [6]:
realY

[30.0,
 41.0,
 44.0,
 33.0,
 37.0,
 36.0,
 45.0,
 42.0,
 49.0,
 45.0,
 44.0,
 41.0,
 30.0,
 24.0,
 13.0,
 22.0,
 25.0,
 34.0,
 38.0,
 50.0,
 53.0,
 43.0,
 43.0,
 45.0,
 46.0,
 32.0,
 16.0,
 19.0,
 22.0,
 26.0,
 9.0,
 16.0,
 22.0,
 23.0,
 29.0,
 32.0,
 36.0,
 34.0,
 45.0,
 40.0,
 41.0,
 23.0,
 29.0,
 23.0,
 37.0,
 50.0,
 49.0,
 45.0,
 63.0,
 63.0,
 62.0,
 55.0,
 56.0,
 67.0,
 78.0,
 83.0,
 90.0,
 75.0,
 85.0,
 82.0,
 57.0,
 56.0,
 64.0,
 67.0,
 72.0,
 64.0,
 73.0,
 57.0,
 57.0,
 53.0,
 70.0,
 70.0,
 60.0,
 68.0,
 66.0,
 45.0,
 48.0,
 57.0,
 57.0,
 59.0,
 62.0,
 59.0,
 61.0,
 50.0,
 60.0,
 62.0,
 62.0,
 50.0,
 45.0,
 43.0,
 29.0,
 42.0,
 56.0,
 66.0,
 78.0,
 62.0,
 61.0,
 47.0,
 54.0,
 57.0,
 59.0,
 61.0,
 43.0,
 39.0,
 38.0,
 40.0,
 42.0,
 41.0,
 39.0,
 36.0,
 35.0,
 36.0,
 36.0,
 32.0,
 33.0,
 33.0,
 34.0,
 21.0,
 15.0,
 13.0,
 16.0,
 17.0,
 9.0,
 7.0,
 7.0,
 20.0,
 20.0,
 20.0,
 18.0,
 18.0,
 22.0,
 15.0,
 11.0,
 1.0,
 1.0,
 8.0,
 4.0,
 8.0,
 12.0,
 19.0,
 23.0,
 20.0,
 18.0,
 15.0,
 

In [7]:
realX

[array([[13.111111  ],
        [ 1.8000001 ],
        [ 0.43888888],
        [ 0.14      ],
        [ 1.9666666 ],
        [ 8.955556  ],
        [10.955555  ],
        [23.88889   ],
        [27.        ],
        [28.777779  ],
        [ 0.        ],
        [71.55556   ],
        [ 2.0666666 ],
        [ 1.9444444 ],
        [88.333336  ],
        [90.37778   ],
        [ 1.5666667 ],
        [ 1.0333333 ]], dtype=float32),
 array([[ 13.444445  ],
        [  1.8000001 ],
        [  0.4644445 ],
        [  0.14333333],
        [  2.7444444 ],
        [  9.511111  ],
        [ 12.288889  ],
        [ 25.333334  ],
        [ 25.        ],
        [ 29.222221  ],
        [  0.        ],
        [ 69.22222   ],
        [  3.5333335 ],
        [  1.9444444 ],
        [ 89.333336  ],
        [103.48889   ],
        [  1.5000001 ],
        [  1.0111111 ]], dtype=float32),
 array([[ 14.111111  ],
        [  1.8000001 ],
        [  0.48444447],
        [  0.14888889],
        [  3.1444445 ],


In [8]:
print(len(realY))
print(len(realX))

3600
3600


In [9]:
realY[3597:3600]   # comforming data read correctly

[17.0, 24.0, 29.0]

In [10]:
realX[3599]

array([[ 15.333333  ],
       [  1.7666669 ],
       [  0.4333333 ],
       [  0.17555554],
       [  1.2222222 ],
       [ 12.677777  ],
       [ 13.966666  ],
       [ 23.88889   ],
       [ 37.22222   ],
       [ 24.88889   ],
       [  0.        ],
       [ 69.77778   ],
       [  2.8222222 ],
       [  1.933333  ],
       [139.33333   ],
       [108.666664  ],
       [  1.6555555 ],
       [  1.2555556 ]], dtype=float32)

In [11]:
def getPower(x):
    outputList = []
    for i in range(len(x)):
        arr = x[i]
        arr.reshape((18,1))
        power2 = np.power(arr, 2)
        power3 = np.power(arr, 3)
        arr = np.vstack((arr, power2, power3))
        outputList.append(arr)
    
    return outputList

In [12]:
xLabel = getPower(realX)
print(xLabel[0].shape)   # check data

(54, 1)


In [13]:
print(xLabel[0])   # check data

[[1.31111107e+01]
 [1.80000007e+00]
 [4.38888878e-01]
 [1.40000001e-01]
 [1.96666658e+00]
 [8.95555592e+00]
 [1.09555550e+01]
 [2.38888893e+01]
 [2.70000000e+01]
 [2.87777786e+01]
 [0.00000000e+00]
 [7.15555573e+01]
 [2.06666660e+00]
 [1.94444442e+00]
 [8.83333359e+01]
 [9.03777771e+01]
 [1.56666672e+00]
 [1.03333330e+00]
 [1.71901230e+02]
 [3.24000025e+00]
 [1.92623451e-01]
 [1.96000002e-02]
 [3.86777735e+00]
 [8.02019806e+01]
 [1.20024185e+02]
 [5.70679016e+02]
 [7.29000000e+02]
 [8.28160522e+02]
 [0.00000000e+00]
 [5.12019775e+03]
 [4.27111101e+00]
 [3.78086400e+00]
 [7.80277832e+03]
 [8.16814258e+03]
 [2.45444465e+00]
 [1.06777775e+00]
 [2.25381592e+03]
 [5.83200073e+00]
 [8.45402852e-02]
 [2.74399994e-03]
 [7.60662842e+00]
 [7.18253357e+02]
 [1.31493152e+03]
 [1.36328887e+04]
 [1.96830000e+04]
 [2.38326211e+04]
 [0.00000000e+00]
 [3.66378594e+05]
 [8.82696247e+00]
 [7.35168028e+00]
 [6.89245438e+05]
 [7.38218562e+05]
 [3.84529662e+00]
 [1.10337031e+00]]


# finish cleaning and getting data 

# start inital training

In [24]:
learningRate = 0.00001
regulationRate = 0.01
epoch = 1000

# loss = (y - y1)^2 + sum(wi^2)
# y1 = w1 * x1 + w2 * x1^2 + w3 * x1^3 + w4 * x2 + w5 * x2^2 ..... + b

# in other way for wn
# loss = (cn * wn + c2)^2 + regRate * wn^2 + c3

# so
# dloss/dw = 2(cn * wn + c2) * cn + 2regRate * wn

# for b 
# loss = (c + b)^2 + c1
# dloss/db = 2[c + b]

def train(xLabel, realY, learningRate, regRate, epoch):
    w = np.random.randn(1, len(xLabel[0]))
    b = np.random.rand(1,1)
    print("w = ")
    print(w, "\n")
    print("b = ")
    print(b, "\n")
    for i in range(epoch):
        print(i)
        for j in range(len(realY)): # looping number of dataset
            coreDev = 2 * (np.dot(w, xLabel[j]) + b - realY[j])
#             print(np.dot(w, xLabel[j]))
#             print(xLabel[j])
#             print("j = " + str(j))
#             print("w = ")
#             print(w, "\n\n")
            if j % 10 == 0:
                loss = (np.dot(w, xLabel[j]) + b - realY[j])**2
                print("loss = " + str(loss))
            
            dldb = coreDev
#         update b
            b = b - dldb * learningRate
#         update each w
            for k in range(w.shape[1]):
#                 print("k = " + str(k))
                cn = xLabel[j][k]
#                 print("cn = " + str(cn))
#                 print("w[k] = " + str(w[k]))
#                 dldm = (coreDev * cn + 2 * w[0][k]* regRate) * learningRate
                dldm = coreDev * cn * learningRate
                w[0][k] = w[0][k] - dldm
    
    return w, b
    

# start training

In [25]:
w, b = train(xLabel, realY, learningRate, regulationRate, epoch)    

print(w)
print(b)

w = 
[[-1.23099518  0.86951136  0.6614969  -0.64129741  0.57188889 -0.70910969
   0.89638609 -0.34925407  0.39841665 -1.07443589  0.36313262  0.99099486
  -0.50433056  0.12301015 -1.03472969 -0.74592454  0.11201187 -0.4941759
   0.68309312  1.64747329 -1.92283389 -1.46660369 -0.01820611 -1.04821385
   1.89882461  1.46115513  0.10923307 -0.29174263  0.70122167  0.69068848
   0.2467592   0.47733204  1.758082   -0.27533995  0.10275148  1.58398304
  -1.02719539  0.07632948  0.0524247  -1.71958266  1.11335553  0.80314173
  -0.26637035 -0.9334141  -1.34008515  1.58936298  0.70271693  0.04564673
   0.61128125 -0.51492887  0.71627233  0.2867327   1.17062847 -1.50643128]] 

b = 
[[0.92288405]] 

0
loss = [[5.39602054e+11]]
loss = [[2.91729484e+193]]
loss = [[inf]]
loss = [[inf]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[

<ipython-input-24-27fe8da0d81e>:35: RuntimeWarning: overflow encountered in square
  loss = (np.dot(w, xLabel[j]) + b - realY[j])**2


loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[nan]]
loss = [[n

KeyboardInterrupt: 