In [3]:
import pandas as pd 
import numpy as np 

trainTable = pd.read_csv("train.csv", engine = "python", encoding = "big5")
testTable = pd.read_csv("test.csv", engine = "python", encoding = "big5", names = [1,2,3,4,5,6,7,8,9])

print(trainTable.head(18))

          日期  測站          測項     0     1     2     3     4     5     6  ...  \
0   2014/1/1  豐原    AMB_TEMP    14    14    14    13    12    12    12  ...   
1   2014/1/1  豐原         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8  ...   
2   2014/1/1  豐原          CO  0.51  0.41  0.39  0.37  0.35   0.3  0.37  ...   
3   2014/1/1  豐原        NMHC   0.2  0.15  0.13  0.12  0.11  0.06   0.1  ...   
4   2014/1/1  豐原          NO   0.9   0.6   0.5   1.7   1.8   1.5   1.9  ...   
5   2014/1/1  豐原         NO2    16   9.2   8.2   6.9   6.8   3.8   6.9  ...   
6   2014/1/1  豐原         NOx    17   9.8   8.7   8.6   8.5   5.3   8.8  ...   
7   2014/1/1  豐原          O3    16    30    27    23    24    28    24  ...   
8   2014/1/1  豐原        PM10    56    50    48    35    25    12     4  ...   
9   2014/1/1  豐原       PM2.5    26    39    36    35    31    28    25  ...   
10  2014/1/1  豐原    RAINFALL    NR    NR    NR    NR    NR    NR    NR  ...   
11  2014/1/1  豐原          RH    77    68    67    74

In [4]:
print(testTable.index)
print(testTable.head(18))

MultiIndex([(  'id_0',   'AMB_TEMP'),
            (  'id_0',        'CH4'),
            (  'id_0',         'CO'),
            (  'id_0',       'NMHC'),
            (  'id_0',         'NO'),
            (  'id_0',        'NO2'),
            (  'id_0',        'NOx'),
            (  'id_0',         'O3'),
            (  'id_0',       'PM10'),
            (  'id_0',      'PM2.5'),
            ...
            ('id_239',       'PM10'),
            ('id_239',      'PM2.5'),
            ('id_239',   'RAINFALL'),
            ('id_239',         'RH'),
            ('id_239',        'SO2'),
            ('id_239',        'THC'),
            ('id_239',      'WD_HR'),
            ('id_239', 'WIND_DIREC'),
            ('id_239', 'WIND_SPEED'),
            ('id_239',      'WS_HR')],
           length=4320)
                    1     2     3     4     5     6     7     8     9
id_0 AMB_TEMP      21    21    20    20    19    19    19    18    17
     CH4          1.7   1.7   1.7   1.7   1.7   1.7   1.7  

In [5]:
testTable.replace(["NR"], [0], inplace = True)
testTable = testTable.astype("float")
testTable.loc[:,"RAINFALL",:][2].value_counts()

0.0     223
0.4       3
0.2       3
0.6       2
6.4       1
2.6       1
1.2       1
3.6       1
9.8       1
2.2       1
1.4       1
16.0      1
14.0      1
Name: 2, dtype: int64

In [6]:
test = np.zeros((18,1))
print(test)
current = np.column_stack([test,np.array(testTable.head(18))])
current[:,1:]

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


array([[2.10e+01, 2.10e+01, 2.00e+01, 2.00e+01, 1.90e+01, 1.90e+01,
        1.90e+01, 1.80e+01, 1.70e+01],
       [1.70e+00, 1.70e+00, 1.70e+00, 1.70e+00, 1.70e+00, 1.70e+00,
        1.70e+00, 1.70e+00, 1.80e+00],
       [3.90e-01, 3.60e-01, 3.60e-01, 4.00e-01, 5.30e-01, 5.50e-01,
        3.40e-01, 3.10e-01, 2.30e-01],
       [1.60e-01, 2.40e-01, 2.20e-01, 2.70e-01, 2.70e-01, 2.60e-01,
        2.70e-01, 2.90e-01, 1.00e-01],
       [1.30e+00, 1.30e+00, 1.30e+00, 1.30e+00, 1.40e+00, 1.60e+00,
        1.20e+00, 1.10e+00, 9.00e-01],
       [1.70e+01, 1.40e+01, 1.30e+01, 1.40e+01, 1.80e+01, 2.10e+01,
        8.90e+00, 9.40e+00, 5.00e+00],
       [1.80e+01, 1.60e+01, 1.40e+01, 1.50e+01, 2.00e+01, 2.30e+01,
        1.00e+01, 1.00e+01, 5.80e+00],
       [3.20e+01, 3.10e+01, 3.10e+01, 2.60e+01, 1.60e+01, 1.20e+01,
        2.70e+01, 2.00e+01, 2.60e+01],
       [6.20e+01, 5.00e+01, 4.40e+01, 3.90e+01, 3.80e+01, 3.20e+01,
        4.80e+01, 3.60e+01, 2.50e+01],
       [3.30e+01, 3.90e+01, 3.90e+01,

In [7]:
trainDataTable = trainTable["0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23".split(" ")]
trainDataTable

0     1     2     3     4     5     6     7     8     9  ...    14  \
0       14    14    14    13    12    12    12    12    15    17  ...    22   
1      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8  ...   1.8   
2     0.51  0.41  0.39  0.37  0.35   0.3  0.37  0.47  0.78  0.74  ...  0.37   
3      0.2  0.15  0.13  0.12  0.11  0.06   0.1  0.13  0.26  0.23  ...   0.1   
4      0.9   0.6   0.5   1.7   1.8   1.5   1.9   2.2   6.6   7.9  ...   2.5   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
4315   1.8   1.8   1.8   1.8   1.8   1.7   1.7   1.8   1.8   1.8  ...   1.8   
4316    46    13    61    44    55    68    66    70    66    85  ...    59   
4317    36    55    72   327    74    52    59    83   106   105  ...    18   
4318   1.9   2.4   1.9   2.8   2.3   1.9   2.1   3.7   2.8   3.8  ...   2.3   
4319   0.7   0.8   1.8     1   1.9   1.7   2.1     2     2   1.7  ...   1.3   

        15    16    17    18    19    20    21    22    23  
0       22    21    19    17    16    15    15    15    15  
1      1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8  
2     0.37  0.47  0.69  0.56  0.45  0.38  0.35  0.36  0.32  
3     0.13  0.14  0.23  0.18  0.12   0.1  0.09   0.1  0.08  
4      2.2   2.5   2.3   2.1   1.9   1.5   1.6   1.8   1.5  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
4315   1.8     2   2.1     2   1.9   1.9   1.9     2     2  
4316   308   327    21   100   109   108   114   108   109  
4317   311    52    54   121    97   107   118   100   105  
4318   2.6   1.3     1   1.5     1   1.7   1.5     2     2  
4319   1.7   0.7   0.4   1.1   1.4   1.3   1.6   1.8     2  

[4320 rows x 24 columns]

In [20]:
dataset = trainDataTable.iloc[0:18, 0:9]
pm = trainDataTable.iloc[9, 9]

print(type(dataset.shape))
dataset

<class 'tuple'>


0     1     2     3     4     5     6     7     8
0     14    14    14    13    12    12    12    12    15
1    1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
2   0.51  0.41  0.39  0.37  0.35   0.3  0.37  0.47  0.78
3    0.2  0.15  0.13  0.12  0.11  0.06   0.1  0.13  0.26
4    0.9   0.6   0.5   1.7   1.8   1.5   1.9   2.2   6.6
5     16   9.2   8.2   6.9   6.8   3.8   6.9   7.8    15
6     17   9.8   8.7   8.6   8.5   5.3   8.8   9.9    22
7     16    30    27    23    24    28    24    22    21
8     56    50    48    35    25    12     4     2    11
9     26    39    36    35    31    28    25    20    19
10     0     0     0     0     0     0     0     0     0
11    77    68    67    74    72    73    74    73    66
12   1.8     2   1.7   1.6   1.9   1.4   1.5   1.6   5.1
13     2     2     2   1.9   1.9   1.8   1.9   1.9   2.1
14    37    80    57    76   110   106   101   104   124
15    35    79   2.4    55    94   116   106    94   232
16   1.4   1.8     1   0.6   1.7   2.5   2.5     2   0.6
17   0.5   0.9   0.6   0.3   0.6   1.9     2     2   0.5

In [12]:
pm

'30'

In [18]:
dataset.replace("NR", "0", inplace = True)

dataset = dataset.astype("float32")

arr = np.array(dataset)

avg = arr.mean(axis = 1)

avg

array([13.111111  ,  1.8000001 ,  0.43888888,  0.14      ,  1.9666666 ,
        8.955556  , 10.955555  , 23.88889   , 27.        , 28.777779  ,
        0.        , 71.55556   ,  2.0666666 ,  1.9444444 , 88.333336  ,
       90.37778   ,  1.5666667 ,  1.0333333 ], dtype=float32)

In [19]:
avg.shape

(18,)

In [22]:
for i in range(0,23):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22


In [24]:
arr = np.array([1,2,3]).reshape((3,1))
arr.shape

(3, 1)

In [25]:
arr

array([[1],
       [2],
       [3]])

In [26]:
a = np.array([1,2,3])
b = np.array([[4], [5], [6]])
print(a.dot(b))

[32]


In [28]:
np.dot(a,b)

array([32])

In [29]:
a[0]

1

In [30]:
a[0] = 5
a

array([5, 2, 3])

In [31]:
type(a)

numpy.ndarray