# initaling data

In [1]:
import pandas as pd
import numpy as np

testTable = pd.read_csv("test.csv", engine = "python", encoding = "big5", names = [1,2,3,4,5,6,7,8,9])

testTable.head(18)

1     2     3     4     5     6     7     8     9
id_0 AMB_TEMP      21    21    20    20    19    19    19    18    17
     CH4          1.7   1.7   1.7   1.7   1.7   1.7   1.7   1.7   1.8
     CO          0.39  0.36  0.36   0.4  0.53  0.55  0.34  0.31  0.23
     NMHC        0.16  0.24  0.22  0.27  0.27  0.26  0.27  0.29   0.1
     NO           1.3   1.3   1.3   1.3   1.4   1.6   1.2   1.1   0.9
     NO2           17    14    13    14    18    21   8.9   9.4     5
     NOx           18    16    14    15    20    23    10    10   5.8
     O3            32    31    31    26    16    12    27    20    26
     PM10          62    50    44    39    38    32    48    36    25
     PM2.5         33    39    39    25    18    18    17     9     4
     RAINFALL      NR    NR    NR    NR    NR    NR    NR    NR    NR
     RH            83    85    87    87    86    85    78    81    80
     SO2            2   1.8   1.8   1.8   2.1   2.6     2   2.3   2.4
     THC          1.8   1.9   1.9     2     2     2     2     2   1.9
     WD_HR         58    53    67    59    59    73    79    82   104
     WIND_DIREC    57    44    73    44    56   115    45   107   103
     WIND_SPEED   1.4   1.3   1.5   1.4   1.6   1.6   1.2   1.8   2.3
     WS_HR          1   0.9   0.9   0.9   1.2   0.7     1   0.6   1.8

In [2]:
weightTable = pd.read_csv("weights.csv")
weightTable

Unnamed: 0         0         1         2         3         4        5  \
0           0 -0.324822  0.087999  0.140063  1.466151  1.172056  0.87631   

          6         7         8         9        10        11      12  \
0 -1.719074 -0.089085  0.594534  0.229374 -2.009028  0.357474  0.2689   

         13        14        15        16        17  
0 -1.581644 -0.003609 -0.046271  0.732081 -0.823042

In [3]:
biasTable = pd.read_csv("bias.csv")
biasTable

Unnamed: 0         0
0           0  0.761157

In [7]:
w = np.array(weightTable.iloc[0,1:])
w

array([-0.32482193,  0.08799866,  0.14006284,  1.46615058,  1.17205639,
        0.8763097 , -1.71907373, -0.08908546,  0.59453446,  0.22937384,
       -2.00902757,  0.35747438,  0.26889988, -1.58164443, -0.00360921,
       -0.04627118,  0.73208147, -0.82304172])

In [10]:
b = np.array(biasTable.iloc[0,1:])
b

array([0.76115671])

In [15]:
testTable.replace("NR", "0", inplace = True)

In [27]:
def readData(df, rowStep, columnStep):
    rowNum = df.shape[0]
    columnNum = df.shape[1]
    output = []
    for i in range(0, rowNum, rowStep):
        dataTable = df.iloc[i:i + rowStep, 0:columnStep]
        arr = np.array(dataTable, dtype = "float")
        arrAvg = arr.mean(axis = 1)
        output.append(arrAvg.reshape(18,1))
    return output

In [28]:
xInput = readData(testTable, 18, 9)
xInput

[array([[19.33333333],
        [ 1.71111111],
        [ 0.38555556],
        [ 0.23111111],
        [ 1.26666667],
        [13.36666667],
        [14.64444444],
        [24.55555556],
        [41.55555556],
        [22.44444444],
        [ 0.        ],
        [83.55555556],
        [ 2.08888889],
        [ 1.94444444],
        [70.44444444],
        [71.55555556],
        [ 1.56666667],
        [ 1.        ]]),
 array([[ 13.        ],
        [  1.77777778],
        [  0.36444444],
        [  0.13555556],
        [  0.65555556],
        [  8.3       ],
        [  8.95555556],
        [ 26.33333333],
        [ 43.44444444],
        [ 18.77777778],
        [  0.        ],
        [ 79.22222222],
        [  1.66666667],
        [  1.87777778],
        [103.11111111],
        [105.33333333],
        [  1.86666667],
        [  1.9       ]]),
 array([[3.08888889e+01],
        [1.74444444e+00],
        [4.38888889e-01],
        [1.83333333e-01],
        [6.00000000e-01],
        [1.21111111e

# start getting result

In [29]:
label = []
pm = []  # pm 2.5

for i in range(len(xInput)):
    label.append("id" + str(i))
    xArr = xInput[i]
    y = np.dot(w, xArr) + b 
    pm.append(y)

print(label)
print(pm)

['id0', 'id1', 'id2', 'id3', 'id4', 'id5', 'id6', 'id7', 'id8', 'id9', 'id10', 'id11', 'id12', 'id13', 'id14', 'id15', 'id16', 'id17', 'id18', 'id19', 'id20', 'id21', 'id22', 'id23', 'id24', 'id25', 'id26', 'id27', 'id28', 'id29', 'id30', 'id31', 'id32', 'id33', 'id34', 'id35', 'id36', 'id37', 'id38', 'id39', 'id40', 'id41', 'id42', 'id43', 'id44', 'id45', 'id46', 'id47', 'id48', 'id49', 'id50', 'id51', 'id52', 'id53', 'id54', 'id55', 'id56', 'id57', 'id58', 'id59', 'id60', 'id61', 'id62', 'id63', 'id64', 'id65', 'id66', 'id67', 'id68', 'id69', 'id70', 'id71', 'id72', 'id73', 'id74', 'id75', 'id76', 'id77', 'id78', 'id79', 'id80', 'id81', 'id82', 'id83', 'id84', 'id85', 'id86', 'id87', 'id88', 'id89', 'id90', 'id91', 'id92', 'id93', 'id94', 'id95', 'id96', 'id97', 'id98', 'id99', 'id100', 'id101', 'id102', 'id103', 'id104', 'id105', 'id106', 'id107', 'id108', 'id109', 'id110', 'id111', 'id112', 'id113', 'id114', 'id115', 'id116', 'id117', 'id118', 'id119', 'id120', 'id121', 'id122', 'i

In [31]:
dict = {'id':label, 'pm2.5' : pm}
outputTable = pd.DataFrame(dict)
outputTable

id                 pm2.5
0      id0   [34.82851738686807]
1      id1   [37.73642558518842]
2      id2    [49.4663136561979]
3      id3   [39.82124712421356]
4      id4  [23.000629751064956]
..     ...                   ...
235  id235   [58.29411013105091]
236  id236   [71.30723491210222]
237  id237    [40.3568227837116]
238  id238  [11.789715636718205]
239  id239  [13.605911454186854]

[240 rows x 2 columns]

In [33]:
outputTable.to_csv("output.csv")